name: Daily Love Message

on:
  schedule:
    - cron: '0 0 * * *'  # 每小时整点执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run script
      run: python src/main.py 
