name: Daily Love Message

on:
  schedule:
    - cron: '30 0 * * *'  # UTC 0:30 对应北京时间 8:30
  workflow_dispatch:  # 支持手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run script
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python src/main.py 